<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
	<title>艺奇模特管理后台系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">
	
	
	<link href="${basePath }ligerui/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
    <link href="${basePath }ligerui/ligerUI/skins/Gray/css/dialog.css" rel="stylesheet" type="text/css" />
    <link href="${basePath }ligerui/ligerUI/skins/ligerui-icons.css" rel="stylesheet" type="text/css" />
    <!--<script src="${basePath }ligerui/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
    --><script src="${basePath }js/jquery.min.js" type="text/javascript"></script>
    <script src="${basePath }ligerui/jquery-validation/jquery.validate.min.js" type="text/javascript"></script> 
    <script src="${basePath }ligerui/jquery-validation/jquery.metadata.js" type="text/javascript"></script>
    <script src="${basePath }ligerui/jquery-validation/messages_cn.js" type="text/javascript"></script>
    <script src="${basePath }ligerui/jquery-validation/validate.extend.js" type="text/javascript"></script>
    <script src="${basePath }ligerui/ligerUI/js/ligerui.all.js" type="text/javascript"></script>
    <script src="${basePath }ligerui/json2.js" type="text/javascript"></script>
    <script src="${basePath }my97/WdatePicker.js" type="text/javascript"></script>
    <link href="${basePath }css/basis.css" rel="stylesheet" type="text/css" />
    <script src="${basePath }js/basis.js" type="text/javascript"></script>
   <!--  <script src="${basePath }js/content.js" type="text/javascript"></script> -->
     <!-- 悬浮JS -->
   <script type="text/javascript" src="${basePath }js/content6.js"></script>
    <script type="text/javascript">
       $.ajaxSetup({cache:false});
    </script>
    
