/**
*Generated by StarUML(tm) Java Add-In
*  @ Project : basis
*  @ File Name : IEmployeeService.java
*  @ Date : 2012/9/21
*  @ Author : wxliu
*/



package com.basis.core.service;
import com.basis.core.common.Result;
import com.basis.core.domain.Employee;

/**
 * 员工权限接口
 * @author wxliu
 *
 */
public interface ILoginService {
	/**
	 * 登录
	 * @param employee
	 * @return
	 */
	public Result<Employee> queryEmployeeLogin(Employee employee);
	
	
}
