/**
*Generated by StarUML(tm) Java Add-In
*  @ Project : basis
*  @ File Name : IRoleService.java
*  @ Date : 2012/9/21
*  @ Author : wxliu
*/



package com.basis.core.service;
import java.util.List;

import com.basis.core.common.Page;
import com.basis.core.common.Result;
import com.basis.core.condition.RoleCondition;
import com.basis.core.domain.Role;

/**
 * 用户组接口
 * @author wxliu
 *
 */
public interface IRoleService {
	/**
	 * 查询用户组
	 * @param id
	 */
	public Role queryRoleById(String id);
	/**
	 * 分页查询用户组
	 * @param condition
	 */
	public Page<Role> queryRolePage(RoleCondition condition);
	/**
	 * 查询用户组列表
	 * @param condition
	 * @return
	 */
	public List<Role> queryRoleList(RoleCondition condition);
	/**
	 * 修改用户组
	 * @param role
	 */
	public Result<Object> modifyRole(Role role);
	/**
	 * 修改用户组
	 * @param role
	 * @return
	 */
	public Result<Object> removeRole(Role role);
	/**
	 * 新增用户组
	 * @param role
	 */
	public Result<String> addRole(Role role);
}
